Update Installer Script

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -1,76 +1,116 @@
-#!/usr/bin/env bash
+#!/usr/bin/env zsh
+tmp=
+
+successfully() {
+  $* || (echo "failed" 1>&2 && exit 1)
+}
+
+function vundle () {
+  vim -c "execute \"BundleInstall\" | q | q"
+}
 
 echo "Checking for SSH key, generating one if it doesn't exist ..."
   [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa
 
 echo "Copying public key to clipboard. Paste it into your Github account ..."
   [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
-  open https://github.com/account/ssh
-  read -p "Press any key once you have pasted into your Github account..."
+  successfully open https://github.com/account/ssh
+  vared -p "Press any key once you have pasted into your Github account..." tmp
+
+echo "Fixing permissions ..."
+  successfully sudo chown -R `whoami` /usr/local
 
 echo "Upgrade base gem system to latest version"
-  sudo gem update --system
-  sudo gem clean
+  successfully sudo gem update --system
+  successfully sudo gem clean
 
 echo "Installing Homebrew, a good OS X package manager ..."
-  /usr/bin/ruby -e "$(/usr/bin/curl -fsSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
-  brew update
+  successfully ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
+  successfully brew update
 
-echo "Installing Packages (git, bash-completion, macvim, ack, wget)"
-  brew install git
-  brew install bash-completion
-  brew install macvim
-  brew install ack
-  brew install wget
-  brew install git-extras
-  brew install legit
-  legit install
+echo "Installing Postgres, a good open source relational database ..."
+  successfully brew install postgresql --no-python
+  successfully initdb /usr/local/var/postgres -E utf8
+
+echo "Installing Redis, a good key-value database ..."
+  successfully brew install redis
+
+echo "Installing ack, for searching the contents of files ..."
+  successfully brew install ack
+
+echo "Installing fasd, for fast directory navigation..."
+  successfully brew install fasd
+
+echo "Installing bash-completion, for better bashing ..."
+  successfully brew install bash-completion
+
+echo "Installing macvim, for better editing ..."
+  successfully brew install macvim
+
+echo "Installing wget, for better file downloading ..."
+  successfully brew install wget
+
+echo "Installing git, for better version control ..."
+  successfully brew install git
+  successfully brew install git-extras
+  successfully brew install legit
+  successfully legit install
+
+echo "Installing lastest zsh, for shell"
+  successfully brew install zsh
 
 echo "Fetch dotfiles"
-  git clone git@github.com:damonmorgan/dotfiles.git ~/.dotfiles
+  successfully git clone git@github.com:damonmorgan/dotfiles.git ~/.dotfiles
 
 echo "Install dotfiles"
-  cd ~/.dotfiles
-  git submodule update --init
-  rake install
+  successfully cd ~/.dotfiles
+  successfully git submodule update --init
+  successfully rake install
 
 echo "Fetch better programming font"
-  wget http://www.levien.com/type/myfonts/Inconsolata.otf
-  read -p "Press any key once you have installed the Inconsolata font..."
-
-echo "Launching MacVim"
-  mvim .
-  read -p "Press any key once you have run :BundleInstall inside of MacVim..."
-
-echo "Building Command-T plugin"
-  cd ~/.dotfiles/vim/bundle/command-t
-  rake make
-
-echo "Create development directory"
-  cd ~/
-  mkdir development
-  cd ~/development
-
-echo "Install snippets"
-  git clone git://github.com/scrooloose/snipmate-snippets.git
-  cd ~/development/snipmate-snippets
-  read -p "Press any key once you have edited Rakefile and changed snipmate to snipmate.vim"
-  rake deploy_local
-
-echo "Get better colour scheme for terminal"
-  git clone git://github.com/altercation/solarized.git
-
-echo "Install Databases (sqlite, mysql)"
-  brew install sqlite
-  brew install mysql
-  read -p "Run the scripts indicated to complete installation of mysql and then press any key to continue..."
+  successfully wget http://www.levien.com/type/myfonts/Inconsolata.otf
+  vared -p "Press any key once you have installed the Inconsolata font..." tmp
 
 echo "Install rbenv (a Ruby version manager)"
-  brew install rbenv
-  brew install ruby-build
-  rbenv init -
+  successfully brew install rbenv
+  successfully brew install ruby-build
+  successfully rbenv init - zsh
 
-echo "Install ruby ree 1.8.7 and ruby 1.9.2"
-  rbenv install ree-1.8.7-2011.03
-  rbenv install 1.9.2-p290
-  rbenv rehash
+echo "Install lastest ruby"
+  successfully rbenv install 1.9.3-p327
+  successfully rbenv rehash
+
+echo "Installing pow"
+  successfully brew install pow
+
+echo "install other development languages"
+  successfully brew install node
+  successfully brew install python
+
+echo "Installing standalone Heroku CLI client. You'll need administrative rights on your machine ..."
+  successfully wget -qO- https://toolbelt.heroku.com/install.sh | sh
+
+echo "Installing the heroku-config plugin for pulling config variables locally to be used as ENV variables ..."
+  successfully /usr/local/heroku/bin/heroku plugins:install git://github.com/ddollar/heroku-config.git
+
+echo "Init Vundle and Install"
+  successfully vundle
+
+echo "Building Command-T plugin"
+  successfully cd ~/.dotfiles/vim/bundle/command-t
+  successfully rake make
+
+echo "Create development directory"
+  successfully cd ~/
+  successfully mkdir development
+
+echo "Install snippets"
+  successfully cd ~/development
+  successfully git clone git://github.com/scrooloose/snipmate-snippets.git
+  successfully cd ~/development/snipmate-snippets
+  vared -p "Press any key once you have edited Rakefile and changed snipmate to snipmate.vim" tmp
+  successfully rake deploy_local
+
+echo "Get better colour scheme for terminal"
+  successfully cd ~/development
+  successfully git clone git://github.com/altercation/solarized.git
